CREATE TABLE Player (
  PlayerName VARCHAR(20) PRIMARY KEY,
  SkinID INT UNSIGNED,
  Points INT
);
CREATE TABLE Resource (
  ResourceID VARCHAR(20) PRIMARY KEY,
  immage longblob NOT NULL
);
CREATE TABLE Map (
  MapID INT AUTO_INCREMENT PRIMARY KEY,
  MapData JSON
);
CREATE TABLE BugReport (
  BugID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  BugDescription VARCHAR(150)
);

ALTER TABLE Player
  ADD CONSTRAINT FK_Player_ResourceID
  FOREIGN KEY (SkinID)
  REFERENCES Resource(ResourceID);